config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to:"welcome#profile"
  post '/search' => "welcome#search"
  get '/search_tag' => "welcome#search_tag"

  resources :blogs do
    resources :comments

    member do
      post 'transition'
      get 'preview'
    end

    collection do
      get 'populate_blogs'
      get 'list_blogs'
      get 'published_blogs'
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include TaggingSearch

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one :picture, as: :imageable, dependent: :destroy
  has_many :tags, as: :tagable, dependent: :destroy
  has_many :taggings, through: :tags
  accepts_nested_attributes_for :picture
  attr_accessor :values

  validates :title, length: { minimum: 3, maximum: 15}
  validates :description, presence: true

  scope :publishable_blogs, -> { where(status: ["post-published","post-republished"])}
  scope :paginate_blogs, ->(val) { limit(5).offset(val).order(created_at: :desc) }
  after_create :create_tagging

  def create_tagging
    tag_vals = values.split(',')
    tag_vals.each do |tag_val|
      if (tagging = Tagging.find_by(value: tag_val))
        tag = tags.create
        tag.tagging = tagging
        tag.save
      else
        taggings.create(value: tag_val)
      end
    end
  end

  def self.search(key)
    blog_ids = Comment.search_blog_ids(key)
    blogs = where("title like ? OR description like ? OR id IN(?)", "%#{key}%","%#{key}%", blog_ids)
    taggings = Tagging.search(key)
    blogs << taggings.collect do |tagging|
        search_tagged_blogs(tagging.id)
    end
    blogs.flatten.uniq
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  load_and_authorize_resource only: [:edit, :preview]
  before_action :authenticate_admin, only: [:list_blogs, :populate_blogs]
  before_action :set_blog, only: [:edit, :show, :preview, :update, :transition, :destroy]

  def new
    @blog = Blog.new
    @blog.build_picture
  end

  def index
    @blogs = current_user.blogs
  end

  def edit
    # unless authorized_user?(@blog)
    #   redirect_to root_url, notice: "You are not authorised to edit this blog"
    # end
  end

  def show
  end

  def preview
    # unless authorized_user?(@blog)
    #   redirect_to root_url, notice: "You are not authorised to preview this blog"
    # end
  end

  def transition
    if @blog.update(status: params[:status])
      redirect_to published_blogs_blogs_path, notice: "Blog status changed to #{@blog.status}"
    else
      redirect_to root_url, notice: "Sorry.Unable to change status of blog!"
    end
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    if (@blog.save)
      redirect_to @blog, notice: 'Blog successfully saved'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'blog was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    if @blog.destroy
      redirect_to @blog, notice: 'blog was successfully deleted'
    end
  end

  def published_blogs
    if current_user.admin?
      @blogs = Blog.all
    else
      @blogs = Blog.publishable_blogs
    end
    if @blogs.empty?
      redirect_to root_url, notice: "Sorry.No blogs available!"
    end
  end

  def list_blogs
    if(session[:offset].nil? || session[:offset] < 0)
      session[:offset] = 0
    else
      session[:offset] += params[:offset_val].to_i
    end
    @paginate_blogs = Blog.paginate_blogs(session[:offset])
    respond_to do |format|
      format.js { render 'list_blogs' }
      format.html
    end

  end

  def populate_blogs
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :description, :values, picture_attributes: [:img_url])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def authenticate_admin
    unless current_user.admin?
      redirect_to root_url, notice: "You are not authorised to view this page!"
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper

end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.user.email %></td>
  <td><%= blog.title %></td>
  <td><%= truncate(blog.description, size: 30) %></td>
  <td><%= link_to "View Comments", blog_comments_path(blog)%>
</tr>

app/views/blogs/_form.html.erb
<div>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
  <%= form_for(blog) do |f| %>
    <%= render 'shared/error_messages', resource: blog%>
    <fieldset>
      <legend>Enter blog Details</legend>
      <div class="field">
        <%= f.label :title, 'Title:' %>
        <%= f.text_field :title, size: 20 %>
      </div>
      <div class="field">
        <%= f.label :description, 'Description:' %>
        <%= f.text_area :description %>
      </div>
      <div class="field">
      <%= f.fields_for :picture do |p| %>
        <%= p.label :img_url, 'Image URL:' %>
        <%= p.text_area :img_url %>
      <% end %>
      </div>
      <div class="field">
        <%= f.label :values, 'Tags:' %>
        <%= f.text_area :values %>
      </div>
      <div>
        <%= f.submit "Create" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/blogs/_paginate_blogs.html.erb
<table border = "1", align = "center">
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Date</th>
  </tr>
  <% paginate_blogs.each do |blog|%>
    <tr>
      <td><%= blog.user.email %></td>
      <td><%= blog.title %></td>
      <td><%= truncate(blog.description, size: 30) %></td>
      <td><%= blog.created_at %></td>
    </tr>
  <% end %>
</table>
<div align = "center">
  <% if offset >= 5 %>
    <%= link_to "Prev", list_blogs_blogs_path(offset_val: -5), remote: true, method: :get %>
  <% end %>
  <% unless paginate_blogs.count < 5 %>
    <%= link_to "Next", list_blogs_blogs_path(offset_val: 5), remote: true, method: :get %>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<h1> Edit Blog </h1>

<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<table border="2", align = "center">
  <% if @blogs.present? %>
    <tr>
      <th colspan = "2">Title</th>
      <th >Status</th>
    </tr>
    <% @blogs.each do |blog| %>
      <tr>
        <td colspan = "2"><%= blog.title %></td>
        <% if blog.status == "post-created" %>
          <td><%= button_to 'Publish Blog', transition_blog_path(blog, status: "post-published") %></td>
          <td><%= link_to 'Preview', preview_blog_path(blog) %></td>
        <% else %>
          <td><%= blog.status %></td>
          <td><%= link_to 'View', blog %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% else %>
  <h3>You have not created any blogs yet.Please create one!</h3>
  <% end %>
</table>

app/views/blogs/list_blogs.html.erb
<div align = "center" id = "paginate-blogs">
  <table border = "1", align = "center">
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
    </tr>
    <% @paginate_blogs.each do |blog|%>
      <tr>
        <td><%= blog.user.email %></td>
        <td><%= blog.title %></td>
        <td><%= truncate(blog.description, size: 30) %></td>
        <td><%= blog.created_at %></td>
      </tr>
    <% end %>
  </table>
  <div align = "center">
    <% if session[:offset] >= 5 %>
      <%= link_to "Prev", list_blogs_blogs_path(offset_val: -5), remote: true, method: :get %>
    <% end %>
    <% unless @paginate_blogs.count < 5 %>
      <%= link_to "Next", list_blogs_blogs_path(offset_val: 5), remote: true, method: :get %>
    <% end %>
  </div>
</div>

app/views/blogs/list_blogs.js.erb
$('#paginate-blogs').html("<%= escape_javascript render('paginate_blogs', paginate_blogs: @paginate_blogs, offset: session[:offset]) %>");

app/views/blogs/new.html.erb
<h1> Create Blog </h1>

<%= render 'form', blog: @blog %>

app/views/blogs/populate_blogs.js.erb
$('#pop-data').html("<%= escape_javascript render(@blogs) %>");

app/views/blogs/preview.html.erb
<h4>Your blog preview</h4>
<div align = "center">
  <h1><%= @blog.title %></h1>
  <p>Description: <%= @blog.description %></p>
  <% if @blog.taggings.first.value %>
    <% @blog.taggings.each do |tag| %>
      <%= tag.value %>
    <% end %>
  <% end %>
  <p>
    <%= link_to 'Edit', edit_blog_path(@blog) %>
    <%= link_to 'Destroy', @blog, method: :delete,
      data: { confirm: 'Are you sure?' } %>
  </p>
  <% if @blog.status == "post-banned" %>
    <p>This blog has been banned. Contact admin for help!</p>
  <% else %>
    <p>
      Looks good?
      <%= button_to 'Publish Blog', transition_blog_path(@blog, status: "post-published") %>
    </p>
  <% end %>
</div>

app/views/blogs/published_blogs.html.erb
  <table border = "1" align = "center">
    <tr>
      <th colspan = "3">Title</th>
      <% if current_user.admin? %>
        <th colspan = "3">status</th>
      <% end %>
    </tr>
    <% @blogs.each do |blog| %>
      <tr>
        <td colspan = "3"><%= blog.title %></td>
        <% if current_user.admin? %>
          <td colspan = "3"><%= blog.status %></td>
        <% end %>
        <td><%= link_to 'View', blog %></td>
      </tr>
    <% end %>
  </table>

app/views/blogs/show.html.erb
<div align = "left">
  <h1><%= @blog.title %></h1>
  <% if @blog.picture.present? %>
    <%= image_tag(@blog.picture.img_url, height: 50, width: 50) %>
  <% end %>
  <p>Description: <%= @blog.description %></p>
  <% if @blog.taggings.first %>
    <% @blog.taggings.each do |tag| %>
      <%= tag.value %>
    <% end %>
  <% end %>
  <% if @blog.comments.exists? %>
    <h3>---Comments---</h3>
    <ul>
      <% @blog.comments.each do |comment|%>
        <li>
          <%= comment.post %>
          <% if can? :edit, comment %>
            <%= link_to 'Edit ', edit_blog_comment_path(@blog,comment) %>|
            <%= link_to 'Delete', blog_comment_path(@blog,comment), method: :delete, data: { confirm: 'are you sure?' } %>
          <% end %>
          <% if comment.taggings.first %>
            <% comment.taggings.each do |tag| %>
              <%= tag.value %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= link_to 'Add New Comment', new_blog_comment_path(@blog) %>
  <% if authorized_user?(@blog) %>
    |<%= link_to 'Edit Blog ', edit_blog_path(@blog) %>|
    <%= link_to 'Delete Blog', @blog, method: :delete, data: { confirm: 'are you sure?' } %>
  <% end %>
  <% if current_user.admin? %>
    <% if @blog.status != "post-banned" %>
      <%= button_to 'Unpublish', transition_blog_path(@blog, status: "post-banned") %>
    <% else %>
      <%= button_to 'Republish', transition_blog_path(@blog, status: "post-republished") %>
    <% end %>
  <% end %>
</div>