config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to:"welcome#profile"
  post '/search' => "welcome#search"
  get '/search_tag' => "welcome#search_tag"

  resources :blogs do
    resources :comments

    member do
      post 'transition'
      get 'preview'
    end

    collection do
      get 'populate_blogs'
      get 'list_blogs'
      get 'published_blogs'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def profile
    @taggings = Tagging.all
    render 'profile', locals: { taggings: @taggings }
  end

  def search
    @blogs = Blog.search(params[:key])
    render 'search_result', locals: { blogs: @blogs}
  end


  def search_tag
    @blogs = Blog.search_tagged_blogs(params[:tagging_id])
    render 'search_result', locals: { blogs: @blogs }
  end

end

app/views/welcome/profile.html.erb
<%= link_to 'Create Blog', new_blog_path %><br/>
<% if current_user.blogs.exists? %>
  <%= link_to 'My Blogs', blogs_path %><br/>
<% end %>
<%= link_to 'All Blogs', published_blogs_blogs_path %><br/>
<% if current_user.admin? %>
  <%= link_to 'Blog List', list_blogs_blogs_path(offset_val: 0) %><br/>
  <p>
    Select user to view his blog:
    <%= collection_select(:blog, :user_id, User.all, :id, :email)%>
  </p>
  <p>
    <div id="pop">
      <table border = "1", id = "pop-data">
      </table>
    </div>
  </p>
<% end %>

<div align = "right">
Tag-Cloud<br>
<% @taggings.each do |tagging|%>
  <%= link_to tagging.value, search_tag_path(tagging_id: tagging.id) %><br>
<% end %>
</div>

app/views/welcome/search_result.html.erb
<% if blogs.present? %>
  <p> Blogs: </p>
  <ul>
    <% blogs.each do |blog| %>
        <li>
          <%= blog.title %>
          <%= link_to 'View', blog %>
        </li>
    <% end %>
  </ul>
<% else %>
  No matching results found!
<% end %>